[package]
name = "termpix"
version = "0.1.0"

[dependencies]
ansi_term = "0.7"
docopt = "1.0"
image = "0.23.11"
serde = "1.0"
serde_derive = "1.0"
terminal_size = "*"
resvg = "0.11.0"
usvg = "0.11.0"
